version: "3"
services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=konecta.miratuweb.online
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=konecta.miratuweb.online
      - LETSENCRYPT_EMAIL=admin@miratuweb.online
    volumes:
      - /home/ubuntu/konecta:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    name: nginx-proxy
    external: true
